"""Colocando coluna forma de pagamento

Revision ID: d977585115db
Revises: 
Create Date: 2025-05-13 17:23:21.618592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd977585115db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_transition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagamento', sa.String(length=120), nullable=False))

    with op.batch_alter_table('transition', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pagamento', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transition', schema=None) as batch_op:
        batch_op.drop_column('pagamento')

    with op.batch_alter_table('fixed_transition', schema=None) as batch_op:
        batch_op.drop_column('pagamento')

    # ### end Alembic commands ###
